--- 

    - name: Gather facts now...
      setup:

    # Yum Install programs & update...
    # We do these individually so we can output individual status
    #  and verify which items were needed or not

#    - name: upgrade all packages
#      yum: name=* state=latest
#
#
#    - name: Install screen
#      yum: name=screen state=latest
#
#
#    - name: Install Z Shell
#      yum: name=zsh state=latest

    # UPDATE HERE - later versions of Ansible have a better authorized_keys module
    # Add the ssh allow file
#    - file:
#        path: /home/{{ base_host_user }}/.ssh/
#        owner: '{{ base_host_user }}'
#        group: '{{ base_host_user }}'
#        mode: 0700
#        state: directory
#    - raw: touch /home/{{ base_host_user }}/.ssh/authorized_keys
#    - file: path=/home/{{ base_host_user }}/.ssh/authorized_keys owner=chris group=chris mode=0600
#    - file: path=/home/mgmt/.ssh/ owner=mgmt group=mgmt mode=0700 state=directory
#    - raw: touch /home/mgmt/.ssh/authorized_keys
#    - file: path=/home/mgmt/.ssh/authorized_keys owner=mgmt group=mgmt mode=0600

#    - copy: src=../configs/screen-config/base-screenrc dest=/etc/skel/.screenrc mode=644
#    - copy: src=base-sudoers dest=/etc/sudoers validate='visudo -cf %s' backup=yes mode=440
#    - copy: src=base-sshd_config dest=/etc/ssh/sshd_config backup=yes mode=600
#    - copy: src=base-screenrc dest=/etc/skel/.screenrc mode=644


    - name: Add Rsyslog RPM keys
      rpm_key:
        key: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
        state: present


    - name: Add Rsyslog repository
      yum_repository:
        name: rsyslog-repository
        description: Rsyslog Repository
#        baseurl: http://yum.puppetlabs.com/el/{{ ansible_distribution_major_version }}/PC1/$basearch
        baseurl: http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
        enabled: yes
        gpgcheck: yes


    - name: Install a more modern version of rsyslog 
      yum:
        name: rsyslog
        state: latest


    - name: Stop the rsyslog service while we edit the configuration
      service:
        name: rsyslog
        state: stopped


    - name: Remove the default log format
      lineinfile:
       path: /etc/rsyslog.conf
       state: absent
       regexp: 'RSYSLOG_TraditionalFileFormat'


    - name: Set the RFC5424 logging format as default
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionFileDefaultTemplate RSYSLOG_SyslogProtocol23Format'


    - name: 'Load the modules required: imfile'
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'MODULES'
       regexp: 'imfile'
       line: 'module(load="imfile" PollingInterval="10")'


    - name: 'Load the modules required: imklog'
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'MODULES'
       regexp: 'imklog'
       line: 'module(load="imklog")'


    - name: 'Load the modules required: imuxsock'
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'MODULES'
       regexp: 'imuxsock'
       line: 'module(load="imuxsock")'


    - name: Set the repeated message reduction paraemter
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$RepeatedMsgReduction off'


    - name: Ensure the working directory is present
      file:
        path: /var/spool/rsyslog
        owner: 'root'
        group: 'root'
        mode: 0744
        state: directory


    - name: Set the working directory to queue logs in
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$WorkDirectory /var/spool/rsyslog'


    - name: Set the retry count parameter
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionResumeRetryCount -1'


    - name: Set the log queue type
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionQueueType LinkedList'


    - name: Set the save log queue on shutdown parameter
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionQueueSaveOnShutdown on'


    - name: Set the save log queue disk size
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionQueueMaxDiskSpace 500M'


    - name: Setup the save log queue
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$ActionQueueFileName mainqueue'


    - name: Set rsyslog debugging level
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$DebugLevel 2'


    - name: Enable rsyslog debugging
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       insertafter: 'GLOBAL DIRECTIVES'
       line: '$DebugFile /var/log/rsyslog-debug.log'


    - name: Ship log files to logstash server
      lineinfile:
       path: /etc/rsyslog.conf
       state: present
       regexp: 'EOF'
       line: '*.* @@logstash.drunkenidiot.org:5001'


    - name: Start the rsyslog service with we the new configuration
      service:
        name: rsyslog
        state: started
        enabled: yes

#    - name: Set NETWORK name parameter
#     lineinfile:
#       path: /etc/sysconfig/network
#       state: present
#       regexp: '(?i)^HOSTNAME'
#       line: 'HOSTNAME={{ short_host_name }}.{{ host_tld }}'


#   - name: Ensure the /etc/hostname file has the proper name in it
#     lineinfile:
#       path: /etc/hostname
#       state: present
#       regexp: '.'
#       line: '{{ short_host_name }}.{{ host_tld }}'


#   - name: Ensure the hosts IPv4 address is in /etc/hosts
#     lineinfile:
#       path: /etc/hosts
#       state: present
#       regexp: '{{ ansible_default_ipv4.address }}'
#       line: '{{ ansible_default_ipv4.address }} {{ short_host_name }} {{ short_host_name }}.{{ host_tld }}'

